#%RAML 1.0
title: Amazon CloudHSM
version: '2014-05-30'
description: ''
mediaType:
- application/json
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
types:
  AZ:
    type: string
    pattern: '[a-zA-Z0-9\-]*'
  AZList:
    type: array
    items:
      type: AZ
  Certificate:
    type: string
    pattern: '[\w :+=./\n-]*'
    minLength: 600
    maxLength: 2400
  CertificateFingerprint:
    type: string
    pattern: ([0-9a-fA-F][0-9a-fA-F]:){15}[0-9a-fA-F][0-9a-fA-F]
  ClientArn:
    type: string
    pattern: arn:aws(-iso)?:cloudhsm:[a-zA-Z0-9\-]*:[0-9]{12}:client-[0-9a-f]{8}
  ClientLabel:
    type: string
    pattern: '[a-zA-Z0-9_.-]{2,64}'
  ClientList:
    type: array
    items:
      type: ClientArn
  ClientToken:
    type: string
    pattern: '[a-zA-Z0-9]{1,64}'
  ClientVersion:
    type: string
    enum:
    - '5.1'
    - '5.3'
  CloudHsmObjectState:
    type: string
    enum:
    - READY
    - UPDATING
    - DEGRADED
  EniId:
    type: string
    pattern: eni-[0-9a-f]{8}
  ExternalId:
    type: string
    pattern: '[\w :+=./-]*'
  HapgArn:
    type: string
    pattern: arn:aws(-iso)?:cloudhsm:[a-zA-Z0-9\-]*:[0-9]{12}:hapg-[0-9a-f]{8}
  HapgList:
    type: array
    items:
      type: HapgArn
  HsmArn:
    type: string
    pattern: arn:aws(-iso)?:cloudhsm:[a-zA-Z0-9\-]*:[0-9]{12}:hsm-[0-9a-f]{8}
    description: <p>An ARN that identifies an HSM.</p>
  HsmList:
    type: array
    items:
      type: HsmArn
    description: <p>Contains a list of ARNs that identify the HSMs.</p>
  HsmSerialNumber:
    type: string
    pattern: \d{1,16}
  HsmStatus:
    type: string
    enum:
    - PENDING
    - RUNNING
    - UPDATING
    - SUSPENDED
    - TERMINATING
    - TERMINATED
    - DEGRADED
  IamRoleArn:
    type: string
    pattern: arn:aws(-iso)?:iam::[0-9]{12}:role/[a-zA-Z0-9_\+=,\.\-@]{1,64}
  IpAddress:
    type: string
    pattern: \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}
  Label:
    type: string
    pattern: '[a-zA-Z0-9_.-]{1,64}'
  PaginationToken:
    type: string
    pattern: '[a-zA-Z0-9+/]*'
  PartitionArn:
    type: string
    pattern: arn:aws(-iso)?:cloudhsm:[a-zA-Z0-9\-]*:[0-9]{12}:hsm-[0-9a-f]{8}/partition-[0-9]{6,12}
  PartitionList:
    type: array
    items:
      type: PartitionArn
  PartitionSerial:
    type: string
    pattern: \d{6,12}
  PartitionSerialList:
    type: array
    items:
      type: PartitionSerial
  SshKey:
    type: string
    pattern: '[a-zA-Z0-9+/= ._:\\@-]*'
  String:
    type: string
    pattern: '[\w :+=./\\-]*'
  SubnetId:
    type: string
    pattern: subnet-[0-9a-f]{8}
  SubscriptionType:
    type: string
    enum:
    - PRODUCTION
    description: <p>Specifies the type of subscription for the HSM.</p> <ul> <li><b>PRODUCTION</b> - The HSM is being used in a production environment.</li> <li><b>TRIAL</b> - The HSM is being used in a product trial.</li> </ul>
  TagKey:
    type: string
    minLength: 1
    maxLength: 128
  TagKeyList:
    type: array
    items:
      type: TagKey
  TagList:
    type: array
    items:
      type: Tag
  TagValue:
    type: string
    minLength: 0
    maxLength: 256
  Timestamp:
    type: string
    pattern: \d*
  VpcId:
    type: string
    pattern: vpc-[0-9a-f]{8}
  AddTagsToResourceRequest:
    type: object
    properties:
      ResourceArn:
        type: String
        description: <p>The Amazon Resource Name (ARN) of the AWS CloudHSM resource to tag.</p>
      TagList:
        type: TagList
        description: <p>One or more tags.</p>
  AddTagsToResourceResponse:
    type: object
    properties:
      Status:
        type: String
        description: <p>The status of the operation.</p>
  CreateHapgRequest:
    type: object
    properties:
      Label:
        type: Label
        description: <p>The label of the new high-availability partition group.</p>
    description: <p>Contains the inputs for the <a>CreateHapgRequest</a> action.</p>
  CreateHapgResponse:
    type: object
    properties:
      HapgArn?:
        type: HapgArn
        description: <p>The ARN of the high-availability partition group.</p>
    description: <p>Contains the output of the <a>CreateHAPartitionGroup</a> action.</p>
  CreateHsmRequest:
    type: object
    properties:
      SubnetId:
        type: SubnetId
        description: <p>The identifier of the subnet in your VPC in which to place the HSM.</p>
      SshKey:
        type: SshKey
        description: <p>The SSH public key to install on the HSM.</p>
      EniIp?:
        type: IpAddress
        description: <p>The IP address to assign to the HSM's ENI.</p> <p>If an IP address is not specified, an IP address will be randomly chosen from the CIDR range of the subnet.</p>
      IamRoleArn:
        type: IamRoleArn
        description: <p>The ARN of an IAM role to enable the AWS CloudHSM service to allocate an ENI on your behalf.</p>
      ExternalId?:
        type: ExternalId
        description: <p>The external ID from <b>IamRoleArn</b>, if present.</p>
      SubscriptionType:
        type: SubscriptionType
      ClientToken?:
        type: ClientToken
        description: <p>A user-defined token to ensure idempotence. Subsequent calls to this operation with the same token will be ignored.</p>
      SyslogIp?:
        type: IpAddress
        description: <p>The IP address for the syslog monitoring server. The AWS CloudHSM service only supports one syslog monitoring server.</p>
    description: <p>Contains the inputs for the <a>CreateHsm</a> operation.</p>
  CreateHsmResponse:
    type: object
    properties:
      HsmArn?:
        type: HsmArn
        description: <p>The ARN of the HSM.</p>
    description: <p>Contains the output of the <a>CreateHsm</a> operation.</p>
  CreateLunaClientRequest:
    type: object
    properties:
      Label?:
        type: ClientLabel
        description: <p>The label for the client.</p>
      Certificate:
        type: Certificate
        description: <p>The contents of a Base64-Encoded X.509 v3 certificate to be installed on the HSMs used by this client.</p>
    description: <p>Contains the inputs for the <a>CreateLunaClient</a> action.</p>
  CreateLunaClientResponse:
    type: object
    properties:
      ClientArn?:
        type: ClientArn
        description: <p>The ARN of the client.</p>
    description: <p>Contains the output of the <a>CreateLunaClient</a> action.</p>
  DeleteHapgRequest:
    type: object
    properties:
      HapgArn:
        type: HapgArn
        description: <p>The ARN of the high-availability partition group to delete.</p>
    description: <p>Contains the inputs for the <a>DeleteHapg</a> action.</p>
  DeleteHapgResponse:
    type: object
    properties:
      Status:
        type: String
        description: <p>The status of the action.</p>
    description: <p>Contains the output of the <a>DeleteHapg</a> action.</p>
  DeleteHsmRequest:
    type: object
    properties:
      HsmArn:
        type: HsmArn
        description: <p>The ARN of the HSM to delete.</p>
    description: <p>Contains the inputs for the <a>DeleteHsm</a> operation.</p>
  DeleteHsmResponse:
    type: object
    properties:
      Status:
        type: String
        description: <p>The status of the operation.</p>
    description: <p>Contains the output of the <a>DeleteHsm</a> operation.</p>
  DeleteLunaClientRequest:
    type: object
    properties:
      ClientArn:
        type: ClientArn
        description: <p>The ARN of the client to delete.</p>
  DeleteLunaClientResponse:
    type: object
    properties:
      Status:
        type: String
        description: <p>The status of the action.</p>
  DescribeHapgRequest:
    type: object
    properties:
      HapgArn:
        type: HapgArn
        description: <p>The ARN of the high-availability partition group to describe.</p>
    description: <p>Contains the inputs for the <a>DescribeHapg</a> action.</p>
  DescribeHapgResponse:
    type: object
    properties:
      HapgArn?:
        type: HapgArn
        description: <p>The ARN of the high-availability partition group.</p>
      HapgSerial?:
        type: String
        description: <p>The serial number of the high-availability partition group.</p>
      HsmsLastActionFailed?:
        type: HsmList
      HsmsPendingDeletion?:
        type: HsmList
      HsmsPendingRegistration?:
        type: HsmList
      Label?:
        type: Label
        description: <p>The label for the high-availability partition group.</p>
      LastModifiedTimestamp?:
        type: Timestamp
        description: <p>The date and time the high-availability partition group was last modified.</p>
      PartitionSerialList?:
        type: PartitionSerialList
        description: <p>The list of partition serial numbers that belong to the high-availability partition group.</p>
      State?:
        type: CloudHsmObjectState
        description: <p>The state of the high-availability partition group.</p>
    description: <p>Contains the output of the <a>DescribeHapg</a> action.</p>
  DescribeHsmRequest:
    type: object
    properties:
      HsmArn?:
        type: HsmArn
        description: <p>The ARN of the HSM. Either the <i>HsmArn</i> or the <i>SerialNumber</i> parameter must be specified.</p>
      HsmSerialNumber?:
        type: HsmSerialNumber
        description: <p>The serial number of the HSM. Either the <i>HsmArn</i> or the <i>HsmSerialNumber</i> parameter must be specified.</p>
    description: <p>Contains the inputs for the <a>DescribeHsm</a> operation. </p>
  DescribeHsmResponse:
    type: object
    properties:
      HsmArn?:
        type: HsmArn
        description: <p>The ARN of the HSM.</p>
      Status?:
        type: HsmStatus
        description: <p>The status of the HSM.</p>
      StatusDetails?:
        type: String
        description: <p>Contains additional information about the status of the HSM.</p>
      AvailabilityZone?:
        type: AZ
        description: <p>The Availability Zone that the HSM is in.</p>
      EniId?:
        type: EniId
        description: <p>The identifier of the elastic network interface (ENI) attached to the HSM.</p>
      EniIp?:
        type: IpAddress
        description: <p>The IP address assigned to the HSM's ENI.</p>
      SubscriptionType?:
        type: SubscriptionType
      SubscriptionStartDate?:
        type: Timestamp
        description: <p>The subscription start date.</p>
      SubscriptionEndDate?:
        type: Timestamp
        description: <p>The subscription end date.</p>
      VpcId?:
        type: VpcId
        description: <p>The identifier of the VPC that the HSM is in.</p>
      SubnetId?:
        type: SubnetId
        description: <p>The identifier of the subnet that the HSM is in.</p>
      IamRoleArn?:
        type: IamRoleArn
        description: <p>The ARN of the IAM role assigned to the HSM.</p>
      SerialNumber?:
        type: HsmSerialNumber
        description: <p>The serial number of the HSM.</p>
      VendorName?:
        type: String
        description: <p>The name of the HSM vendor.</p>
      HsmType?:
        type: String
        description: <p>The HSM model type.</p>
      SoftwareVersion?:
        type: String
        description: <p>The HSM software version.</p>
      SshPublicKey?:
        type: SshKey
        description: <p>The public SSH key.</p>
      SshKeyLastUpdated?:
        type: Timestamp
        description: <p>The date and time that the SSH key was last updated.</p>
      ServerCertUri?:
        type: String
        description: <p>The URI of the certificate server.</p>
      ServerCertLastUpdated?:
        type: Timestamp
        description: <p>The date and time that the server certificate was last updated.</p>
      Partitions?:
        type: PartitionList
        description: <p>The list of partitions on the HSM.</p>
    description: <p>Contains the output of the <a>DescribeHsm</a> operation.</p>
  DescribeLunaClientRequest:
    type: object
    properties:
      ClientArn?:
        type: ClientArn
        description: <p>The ARN of the client.</p>
      CertificateFingerprint?:
        type: CertificateFingerprint
        description: <p>The certificate fingerprint.</p>
  DescribeLunaClientResponse:
    type: object
    properties:
      ClientArn?:
        type: ClientArn
        description: <p>The ARN of the client.</p>
      Certificate?:
        type: Certificate
        description: <p>The certificate installed on the HSMs used by this client.</p>
      CertificateFingerprint?:
        type: CertificateFingerprint
        description: <p>The certificate fingerprint.</p>
      LastModifiedTimestamp?:
        type: Timestamp
        description: <p>The date and time the client was last modified.</p>
      Label?:
        type: Label
        description: <p>The label of the client.</p>
  GetConfigRequest:
    type: object
    properties:
      ClientArn:
        type: ClientArn
        description: <p>The ARN of the client.</p>
      ClientVersion:
        type: ClientVersion
        description: <p>The client version.</p>
      HapgList:
        type: HapgList
        description: <p>A list of ARNs that identify the high-availability partition groups that are associated with the client.</p>
  GetConfigResponse:
    type: object
    properties:
      ConfigType?:
        type: String
        description: <p>The type of credentials.</p>
      ConfigFile?:
        type: String
        description: <p>The chrystoki.conf configuration file.</p>
      ConfigCred?:
        type: String
        description: <p>The certificate file containing the server.pem files of the HSMs.</p>
  ListAvailableZonesRequest:
    type: object
    description: <p>Contains the inputs for the <a>ListAvailableZones</a> action.</p>
  ListAvailableZonesResponse:
    type: object
    properties:
      AZList?:
        type: AZList
        description: <p>The list of Availability Zones that have available AWS CloudHSM capacity.</p>
  ListHapgsRequest:
    type: object
    properties:
      NextToken?:
        type: PaginationToken
        description: <p>The <i>NextToken</i> value from a previous call to <a>ListHapgs</a>. Pass null if this is the first call.</p>
  ListHapgsResponse:
    type: object
    properties:
      HapgList:
        type: HapgList
        description: <p>The list of high-availability partition groups.</p>
      NextToken?:
        type: PaginationToken
        description: <p>If not null, more results are available. Pass this value to <a>ListHapgs</a> to retrieve the next set of items.</p>
  ListHsmsRequest:
    type: object
    properties:
      NextToken?:
        type: PaginationToken
        description: <p>The <i>NextToken</i> value from a previous call to <a>ListHsms</a>. Pass null if this is the first call.</p>
  ListHsmsResponse:
    type: object
    properties:
      HsmList?:
        type: HsmList
        description: <p>The list of ARNs that identify the HSMs.</p>
      NextToken?:
        type: PaginationToken
        description: <p>If not null, more results are available. Pass this value to <a>ListHsms</a> to retrieve the next set of items.</p>
    description: <p>Contains the output of the <a>ListHsms</a> operation.</p>
  ListLunaClientsRequest:
    type: object
    properties:
      NextToken?:
        type: PaginationToken
        description: <p>The <i>NextToken</i> value from a previous call to <a>ListLunaClients</a>. Pass null if this is the first call.</p>
  ListLunaClientsResponse:
    type: object
    properties:
      ClientList:
        type: ClientList
        description: <p>The list of clients.</p>
      NextToken?:
        type: PaginationToken
        description: <p>If not null, more results are available. Pass this to <a>ListLunaClients</a> to retrieve the next set of items.</p>
  ListTagsForResourceRequest:
    type: object
    properties:
      ResourceArn:
        type: String
        description: <p>The Amazon Resource Name (ARN) of the AWS CloudHSM resource.</p>
  ListTagsForResourceResponse:
    type: object
    properties:
      TagList:
        type: TagList
        description: <p>One or more tags.</p>
  ModifyHapgRequest:
    type: object
    properties:
      HapgArn:
        type: HapgArn
        description: <p>The ARN of the high-availability partition group to modify.</p>
      Label?:
        type: Label
        description: <p>The new label for the high-availability partition group.</p>
      PartitionSerialList?:
        type: PartitionSerialList
        description: <p>The list of partition serial numbers to make members of the high-availability partition group.</p>
  ModifyHapgResponse:
    type: object
    properties:
      HapgArn?:
        type: HapgArn
        description: <p>The ARN of the high-availability partition group.</p>
  ModifyHsmRequest:
    type: object
    properties:
      HsmArn:
        type: HsmArn
        description: <p>The ARN of the HSM to modify.</p>
      SubnetId?:
        type: SubnetId
        description: <p>The new identifier of the subnet that the HSM is in. The new subnet must be in the same Availability Zone as the current subnet.</p>
      EniIp?:
        type: IpAddress
        description: <p>The new IP address for the elastic network interface (ENI) attached to the HSM.</p> <p>If the HSM is moved to a different subnet, and an IP address is not specified, an IP address will be randomly chosen from the CIDR range of the new subnet.</p>
      IamRoleArn?:
        type: IamRoleArn
        description: <p>The new IAM role ARN.</p>
      ExternalId?:
        type: ExternalId
        description: <p>The new external ID.</p>
      SyslogIp?:
        type: IpAddress
        description: <p>The new IP address for the syslog monitoring server. The AWS CloudHSM service only supports one syslog monitoring server.</p>
    description: <p>Contains the inputs for the <a>ModifyHsm</a> operation.</p>
  ModifyHsmResponse:
    type: object
    properties:
      HsmArn?:
        type: HsmArn
        description: <p>The ARN of the HSM.</p>
    description: <p>Contains the output of the <a>ModifyHsm</a> operation.</p>
  ModifyLunaClientRequest:
    type: object
    properties:
      ClientArn:
        type: ClientArn
        description: <p>The ARN of the client.</p>
      Certificate:
        type: Certificate
        description: <p>The new certificate for the client.</p>
  ModifyLunaClientResponse:
    type: object
    properties:
      ClientArn?:
        type: ClientArn
        description: <p>The ARN of the client.</p>
  RemoveTagsFromResourceRequest:
    type: object
    properties:
      ResourceArn:
        type: String
        description: <p>The Amazon Resource Name (ARN) of the AWS CloudHSM resource.</p>
      TagKeyList:
        type: TagKeyList
        description: <p>The tag key or keys to remove.</p> <p>Specify only the tag key to remove (not the value). To overwrite the value for an existing tag, use <a>AddTagsToResource</a>.</p>
  RemoveTagsFromResourceResponse:
    type: object
    properties:
      Status:
        type: String
        description: <p>The status of the operation.</p>
  Tag:
    type: object
    properties:
      Key:
        type: TagKey
        description: <p>The key of the tag.</p>
      Value:
        type: TagValue
        description: <p>The value of the tag.</p>
    description: <p>A key-value pair that identifies or specifies metadata about an AWS CloudHSM resource.</p>
/{AddTagsToResource}:
  uriParameters:
    AddTagsToResource?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Add Tags To Resource
  post:
    description: Adds or overwrites one or more tags for the specified AWS CloudHSM resource. Each tag consists of a key and a value. Tag keys must be unique to each resource.
    displayName: Add Tags To Resource
    body:
      application/json: AddTagsToResourceRequest
    responses:
      200:
        body:
          application/json: AddTagsToResourceResponse
      400:
        description: CloudHsmServiceException
/{CreateHapg}:
  uriParameters:
    CreateHapg?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Create Hapg
  post:
    description: Creates a high-availability partition group. A high-availability partition group is a group of partitions that spans multiple physical HSMs.
    displayName: Create Hapg
    body:
      application/json: CreateHapgRequest
    responses:
      200:
        body:
          application/json: CreateHapgResponse
      400:
        description: CloudHsmServiceException
/{CreateHsm}:
  uriParameters:
    CreateHsm?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Create Hsm
  post:
    description: Creates an uninitialized HSM instance. There is an upfront fee charged for each HSM instance that you create with the <a>CreateHsm</a> operation. If you accidentally provision an HSM and want to request a refund, delete the instance using the <a>DeleteHsm</a> operation, go to the <a href="https://console.aws.amazon.com/support/home#/">AWS Support Center</a>, create a new case, and select <b>Account and Billing Support</b>. <important> It can take up to 20 minutes to create and provision an HSM. You can monitor the status of the HSM with the <a>DescribeHsm</a> operation. The HSM is ready to be initialized when the status changes to <code>RUNNING</code>. </important>
    displayName: Create Hsm
    body:
      application/json: CreateHsmRequest
    responses:
      200:
        body:
          application/json: CreateHsmResponse
      400:
        description: CloudHsmServiceException
/{CreateLunaClient}:
  uriParameters:
    CreateLunaClient?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Create Luna Client
  post:
    description: Creates an HSM client.
    displayName: Create Luna Client
    body:
      application/json: CreateLunaClientRequest
    responses:
      200:
        body:
          application/json: CreateLunaClientResponse
      400:
        description: CloudHsmServiceException
/{DeleteHapg}:
  uriParameters:
    DeleteHapg?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Delete Hapg
  post:
    description: Deletes a high-availability partition group.
    displayName: Delete Hapg
    body:
      application/json: DeleteHapgRequest
    responses:
      200:
        body:
          application/json: DeleteHapgResponse
      400:
        description: CloudHsmServiceException
/{DeleteHsm}:
  uriParameters:
    DeleteHsm?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Delete Hsm
  post:
    description: Deletes an HSM. After completion, this operation cannot be undone and your key material cannot be recovered.
    displayName: Delete Hsm
    body:
      application/json: DeleteHsmRequest
    responses:
      200:
        body:
          application/json: DeleteHsmResponse
      400:
        description: CloudHsmServiceException
/{DeleteLunaClient}:
  uriParameters:
    DeleteLunaClient?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Delete Luna Client
  post:
    description: Deletes a client.
    displayName: Delete Luna Client
    body:
      application/json: DeleteLunaClientRequest
    responses:
      200:
        body:
          application/json: DeleteLunaClientResponse
      400:
        description: CloudHsmServiceException
/{DescribeHapg}:
  uriParameters:
    DescribeHapg?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Describe Hapg
  post:
    description: Retrieves information about a high-availability partition group.
    displayName: Describe Hapg
    body:
      application/json: DescribeHapgRequest
    responses:
      200:
        body:
          application/json: DescribeHapgResponse
      400:
        description: CloudHsmServiceException
/{DescribeHsm}:
  uriParameters:
    DescribeHsm?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Describe Hsm
  post:
    description: Retrieves information about an HSM. You can identify the HSM by its ARN or its serial number.
    displayName: Describe Hsm
    body:
      application/json: DescribeHsmRequest
    responses:
      200:
        body:
          application/json: DescribeHsmResponse
      400:
        description: CloudHsmServiceException
/{DescribeLunaClient}:
  uriParameters:
    DescribeLunaClient?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Describe Luna Client
  post:
    description: Retrieves information about an HSM client.
    displayName: Describe Luna Client
    body:
      application/json: DescribeLunaClientRequest
    responses:
      200:
        body:
          application/json: DescribeLunaClientResponse
      400:
        description: CloudHsmServiceException
/{GetConfig}:
  uriParameters:
    GetConfig?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Get Config
  post:
    description: Gets the configuration files necessary to connect to all high availability partition groups the client is associated with.
    displayName: Get Config
    body:
      application/json: GetConfigRequest
    responses:
      200:
        body:
          application/json: GetConfigResponse
      400:
        description: CloudHsmServiceException
/{ListAvailableZones}:
  uriParameters:
    ListAvailableZones?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: List Available Zones
  post:
    description: Lists the Availability Zones that have available AWS CloudHSM capacity.
    displayName: List Available Zones
    body:
      application/json: ListAvailableZonesRequest
    responses:
      200:
        body:
          application/json: ListAvailableZonesResponse
      400:
        description: CloudHsmServiceException
/{ListHapgs}:
  uriParameters:
    ListHapgs?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: List Hapgs
  post:
    description: Lists the high-availability partition groups for the account. This operation supports pagination with the use of the <i>NextToken</i> member. If more results are available, the <i>NextToken</i> member of the response contains a token that you pass in the next call to <a>ListHapgs</a> to retrieve the next set of items.
    displayName: List Hapgs
    body:
      application/json: ListHapgsRequest
    responses:
      200:
        body:
          application/json: ListHapgsResponse
      400:
        description: CloudHsmServiceException
/{ListHsms}:
  uriParameters:
    ListHsms?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: List Hsms
  post:
    description: Retrieves the identifiers of all of the HSMs provisioned for the current customer. This operation supports pagination with the use of the <i>NextToken</i> member. If more results are available, the <i>NextToken</i> member of the response contains a token that you pass in the next call to <a>ListHsms</a> to retrieve the next set of items.
    displayName: List Hsms
    body:
      application/json: ListHsmsRequest
    responses:
      200:
        body:
          application/json: ListHsmsResponse
      400:
        description: CloudHsmServiceException
/{ListLunaClients}:
  uriParameters:
    ListLunaClients?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: List Luna Clients
  post:
    description: Lists all of the clients. This operation supports pagination with the use of the <i>NextToken</i> member. If more results are available, the <i>NextToken</i> member of the response contains a token that you pass in the next call to <a>ListLunaClients</a> to retrieve the next set of items.
    displayName: List Luna Clients
    body:
      application/json: ListLunaClientsRequest
    responses:
      200:
        body:
          application/json: ListLunaClientsResponse
      400:
        description: CloudHsmServiceException
/{ListTagsForResource}:
  uriParameters:
    ListTagsForResource?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: List Tags For Resource
  post:
    description: Returns a list of all tags for the specified AWS CloudHSM resource.
    displayName: List Tags For Resource
    body:
      application/json: ListTagsForResourceRequest
    responses:
      200:
        body:
          application/json: ListTagsForResourceResponse
      400:
        description: CloudHsmServiceException
/{ModifyHapg}:
  uriParameters:
    ModifyHapg?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Modify Hapg
  post:
    description: Modifies an existing high-availability partition group.
    displayName: Modify Hapg
    body:
      application/json: ModifyHapgRequest
    responses:
      200:
        body:
          application/json: ModifyHapgResponse
      400:
        description: CloudHsmServiceException
/{ModifyHsm}:
  uriParameters:
    ModifyHsm?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Modify Hsm
  post:
    description: Modifies an HSM. <important> This operation can result in the HSM being offline for up to 15 minutes while the AWS CloudHSM service is reconfigured. If you are modifying a production HSM, you should ensure that your AWS CloudHSM service is configured for high availability, and consider executing this operation during a maintenance window. </important>
    displayName: Modify Hsm
    body:
      application/json: ModifyHsmRequest
    responses:
      200:
        body:
          application/json: ModifyHsmResponse
      400:
        description: CloudHsmServiceException
/{ModifyLunaClient}:
  uriParameters:
    ModifyLunaClient?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Modify Luna Client
  post:
    description: Modifies the certificate used by the client. This action can potentially start a workflow to install the new certificate on the client's HSMs.
    displayName: Modify Luna Client
    body:
      application/json: ModifyLunaClientRequest
    responses:
      200:
        body:
          application/json: ModifyLunaClientResponse
      400:
        description: CloudHsmServiceException
/{RemoveTagsFromResource}:
  uriParameters:
    RemoveTagsFromResource?:
      type: string
      enum:
      - ''
      (extras.syntetic): true
      description: This url parameter exists only to differentiate different operations on the same url
  displayName: Remove Tags From Resource
  post:
    description: Removes one or more tags from the specified AWS CloudHSM resource. To remove a tag, specify only the tag key to remove (not the value). To overwrite the value for an existing tag, use <a>AddTagsToResource</a>.
    displayName: Remove Tags From Resource
    body:
      application/json: RemoveTagsFromResourceRequest
    responses:
      200:
        body:
          application/json: RemoveTagsFromResourceResponse
      400:
        description: CloudHsmServiceException
